version: '3.8'
services:
  app:
    restart: always
    image: 3b_store
    container_name: 3b_store
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    working_dir: /src
    environment:
      DEBUG: 1
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - ./compose/local/.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: 3b_store_db 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=Store
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  mongo_db:
    image: mongo
    container_name: 3b_store_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    container_name: 3b_store_redis
    ports:
      - '6380:6379'
  celery:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: 3b_store_celery
    working_dir: /src
    command: watchfiles celery.__main__.main --args '-A config.celery_app worker -l INFO'
    env_file:
      - ./compose/local/.env
    volumes:
      - .:/src
    depends_on:
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: 3b_store_celery_beat
    working_dir: /src
    command: watchfiles celery.__main__.main --args '-A config.celery_app beat -l INFO'
    env_file:
      - ./compose/local/.env
    volumes:
      - .:/src
    depends_on:
      - redis
volumes:
  postgres_db:
    driver: local
  mongodb_data:
    driver: local