version: '3.8'
services:
  app:
    restart: always
    image: 3b_store
    container_name: 3b_store
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    working_dir: /src
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: 1
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - ./compose/local/.env
  postgres_db:
    image: postgres:latest
    container_name: 3b_store_db 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=Store
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  mongo_db:
    image: mongo
    container_name: 3b_store_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  postgres_db:
    driver: local
  mongodb_data:
    driver: local